### ISSUE TITLE
Geocoding Error when submit zip code

### ISSUE THREAD

**Issue by JhonsonTian** [mail-my-ballot/mail-my-ballot#12]
@tianhuil , I got this error when I press start Button / submit.

![image](https://user-images.githubusercontent.com/26655399/83373813-e73aeb00-a3f3-11ea-8f7f-cf47d822eda9.png)

I see it is coming from "simple-trpc".

**Comment by tianhuil** [comment]
Thanks for writing.  It looks like you need to either connect your backend server properly or setup the credentials there.  Could you post the stack trace from your server?

**Comment by aHuatDeveloper** [comment]
Solved this issue. I haven't enabled Geocoding and Geolocation API and completely set up a billing account.
Thanks

**Comment by JhonsonTian** [comment]
Solved this issue. I haven't enabled Geocoding and Geolocation API and completely set up a billing account.
Thanks
