### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by KingDev07** [mail-my-ballot/mail-my-ballot#13]
I have already run the project locally after configuration.

For now, I'm having some issues in regards of deployment.
I'm not sure how I can deploy the only client to vercel but I used now --prod in the root directory.
Then I could get the folder deployed like this.
![Screen Shot 2020-06-03 at 04 36 58](https://user-images.githubusercontent.com/49837219/83627309-f2a52800-a553-11ea-9fad-bc95f8b45a41.png)
Next, I navigated packages/client/build to run the client but I got the page with an error.
![Screen Shot 2020-06-03 at 04 41 49](https://user-images.githubusercontent.com/49837219/83627707-9d1d4b00-a554-11ea-914c-479f5b86c338.png)

**Comment by tianhuil** [comment]
Thanks for submitting this question.  It looks like you're trying to deploy a now project from the root and not the client.  Take a look at the various `gulpfile.js`'s (in particular the client one).  You can invoke them via `lerna`.

If you need more references, I would suggest you check out references for `lerna`, `now`, `gulp`, and `gulp`.  There are more instructions in the README.md
